### ISSUE TITLE
Mesh error from `pygmsh`

### ISSUE THREAD

**Issue by krober10nd** [nschloe/meshplex#76]
When building a simple sphere with some variable mesh resolution using `pygmsh` 7.0.0 with `meshplex` faults when I try to load this mesh into  ``meshplex-0.13.3``:

* MWE

```
import time
 
from math import sqrt
import pygmsh
import meshplex
 
 
with pygmsh.occ.Geometry() as geom:
    geom.add_ball([0.0, 0.0, 0.0], 1.0)
 
    geom.set_mesh_size_callback(
        lambda dim, tag, x, y, z: (
            abs(sqrt(x ** 2 + y ** 2 + z ** 2) - 0.5) / 5 + 0.025
        )
        / 1.1
    )
    t1 = time.time()
    mesh = geom.generate_mesh()
    print(time.time() - t1)
 
mesh.write("out.vtk")
 
plex = meshplex.MeshTetra(mesh.points, mesh.cells[1][1])
``` 

produces impressively quickly a sphere that looks ok but errors:

```
(base) keiths-MacBook-Pro:pygmsh Keith$ python ball.py 
4.493945121765137
Traceback (most recent call last):
  File "ball.py", line 24, in <module>
    plex = meshplex.MeshTetra(mesh.points, mesh.cells[1][1])
  File "/Applications/miniconda3/lib/python3.7/site-packages/meshplex/mesh_tetra.py", line 39, in __init__
    numpy.sum(~is_used)
AssertionError: There are 25487 dangling nodes in the mesh
```

**Comment by krober10nd** [comment]
ah I see it should be `mesh.cells[1][2]` to get the tets...
